### ISSUE TITLE
Don't hardcode my own name lol

### ISSUE THREAD

**Issue by jlfwong** [jlfwong/messenger-to-markdown#1]
"Jamie Wong" is hardcoded into the extension right now, which unsurprisingly causes some confusion for other users

**Comment by dufferzafar** [comment]
Hey, I tried the extension today and came here to create this same issue!

What is the straightforward way to fix this?

**Comment by jlfwong** [comment]
The easiest thing is just to replace the hardcoded name: https://github.com/jlfwong/messenger-to-markdown/blob/924e1bc0a0a08e77e01b6feb34dbfa002343eb61/content_script.js#L32

**Comment by dufferzafar** [comment]
No, I meant it in the sense that how would you fix this in general?

For me, `document.querySelectorAll("h5._ih3.accessible_elem").innerText`, returns my name. Is there a better way?

**Comment by jlfwong** [comment]
Thanks for the fix!
